/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Odevler;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author aysek
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
    }
    public boolean kontrol (javax.swing.JLabel lbl1 ,javax.swing.JLabel lbl2,javax.swing.JLabel lbl3){  
        boolean check = false;
        if(lbl1.getText().equals(lbl2.getText()) && lbl1.getText().equals(lbl3.getText())){
            check = true;            
        }else{
            check = false;           
        }
        if(check){
            if(lbl1.getText().equals("X")){
                JOptionPane.showMessageDialog(this, "Birinci oyuncu kazandı.");
            }else{
                JOptionPane.showMessageDialog(this, "İkinci oyuncu kazandı.");
            }
        }
        return check;
    }
    private void locked(javax.swing.JLabel lbl){
        boolean kontrol = lbl.getText().equals("");
        if(kontrol){
        lbl.setEnabled(false);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_11 = new javax.swing.JLabel();
        lbl_21 = new javax.swing.JLabel();
        lbl_12 = new javax.swing.JLabel();
        lbl_23 = new javax.swing.JLabel();
        lbl_31 = new javax.swing.JLabel();
        lbl_32 = new javax.swing.JLabel();
        lbl_13 = new javax.swing.JLabel();
        lbl_22 = new javax.swing.JLabel();
        lbl_33 = new javax.swing.JLabel();
        cb_xo = new javax.swing.JComboBox<>();
        cb_yer = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lbl_33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        cb_xo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "O" }));

        cb_yer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12", "13", "21", "22", "23", "31", "32", "33" }));

        jButton1.setText("oyna");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("sonuç");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_xo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_yer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(cb_xo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_yer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int yer =cb_yer.getSelectedIndex();
        int xo = cb_xo.getSelectedIndex();
        if(yer == 0){
            if(xo == 0){
                lbl_11.setText("X");
                locked(lbl_11);
            }else{
                lbl_11.setText("O");
                locked(lbl_11);

            }
        }else if(yer == 1){
            if(xo == 0){
                lbl_12.setText("X");
            }else{
                lbl_12.setText("O");
            }
        }else if(yer ==2){
            if(xo == 0){
                lbl_13.setText("X");
            }else{
                lbl_13.setText("O");
            }
        }else if(yer == 3){
            if(xo == 0){
                lbl_21.setText("X");
            }else{
                lbl_21.setText("O");
            }
        }else if(yer == 4){
            if(xo == 0){
                lbl_22.setText("X");
            }else{
                lbl_22.setText("O");
            }
        }else if(yer == 5){
            if(xo == 0){
                lbl_23.setText("X");
            }else{
                lbl_23.setText("O");
            }
        }else if(yer ==6){
            if(xo == 0){
                lbl_31.setText("X");
            }else{
                lbl_31.setText("O");
            }
        }else if(yer == 7){
            if(xo == 0){
                lbl_32.setText("X");
            }else{
                lbl_32.setText("O");
            }
        }else{
            if(xo == 0){
                lbl_33.setText("X");
            }else{
                lbl_33.setText("O");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:       
        boolean kontrol1 = kontrol(lbl_11,lbl_12,lbl_13);
        boolean kontrol2 = kontrol(lbl_21,lbl_22,lbl_23);
        boolean kontrol3 = kontrol(lbl_31,lbl_32,lbl_33);
        boolean kontrol4 = kontrol(lbl_11,lbl_21,lbl_31);
        boolean kontrol5 = kontrol(lbl_12,lbl_22,lbl_32);
        boolean kontrol6 = kontrol(lbl_13,lbl_23,lbl_33);
        boolean kontrol7 =kontrol(lbl_11,lbl_22,lbl_33);
        boolean kontrol8 =kontrol(lbl_31,lbl_22,lbl_13);
        ArrayList<Boolean> kontroller = new ArrayList<>();
        kontroller.add(kontrol1);
        kontroller.add(kontrol2);
        kontroller.add(kontrol3);
        kontroller.add(kontrol4);
        kontroller.add(kontrol5);
        kontroller.add(kontrol6);
        kontroller.add(kontrol7);
        kontroller.add(kontrol8);
        if(kontroller.contains(true)){
            return;
        }else{
            JOptionPane.showMessageDialog(null,"Berabere");
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_xo;
    private javax.swing.JComboBox<String> cb_yer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lbl_11;
    private javax.swing.JLabel lbl_12;
    private javax.swing.JLabel lbl_13;
    private javax.swing.JLabel lbl_21;
    private javax.swing.JLabel lbl_22;
    private javax.swing.JLabel lbl_23;
    private javax.swing.JLabel lbl_31;
    private javax.swing.JLabel lbl_32;
    private javax.swing.JLabel lbl_33;
    // End of variables declaration//GEN-END:variables
}
